/** Real, verifiable, NASA-level facts shown on the win/fact card, per GDD §4/§5. */
import type { PlanetId } from './planets';

export const FACTS: Record<PlanetId, string[]> = {
  earth: [
    'Earth is the third planet from the Sun and the only known world with liquid water on its surface.',
    "Earth's equatorial radius is about 6,371 km.",
    'A day on Earth (one full rotation) is 24 hours.',
    'Earth orbits the Sun once every 365.25 days.',
    'About 71% of the surface is covered by ocean.',
    'Earth has one natural satellite: the Moon.',
    'The atmosphere is roughly 78% nitrogen and 21% oxygen.',
    'Average surface gravity is 9.8 m/s².',
    "Earth's average distance from the Sun is about 150 million km (1 AU).",
    'Average global surface temperature is about 15°C (59°F).',
    "Earth's core is mostly solid iron surrounded by a liquid outer core of iron and nickel.",
  ],
  moon: [
    "The Moon is Earth's only natural satellite.",
    'The Moon has no significant atmosphere.',
    'Its radius is about 1,737 km, roughly a quarter of Earth\'s.',
    'It takes about 27.3 days to orbit Earth once.',
    "The Moon is tidally locked, so the same side always faces Earth.",
    'Surface gravity is about 1.6 m/s², roughly one-sixth of Earth\'s.',
    'Daytime temperatures can reach about 127°C, and nighttime lows about -173°C.',
    'The Moon is about 384,400 km from Earth on average.',
    "The dark plains visible from Earth are called maria, ancient basaltic lava flows.",
    'Twelve astronauts have walked on the Moon, during the Apollo missions of 1969-1972.',
    "The Moon is slowly drifting away from Earth, by about 3.8 cm per year.",
  ],
  venus: [
    'Venus is the second planet from the Sun.',
    "Venus is the hottest planet in the Solar System, with a surface temperature around 465°C.",
    "A thick atmosphere of carbon dioxide traps heat in a runaway greenhouse effect.",
    "Surface pressure is about 92 times that of Earth, similar to the deep ocean.",
    "Venus rotates backwards (retrograde) compared to most other planets.",
    'A single Venusian day (one rotation) lasts longer than its year: about 243 Earth days.',
    "Venus's radius is about 6,052 km, close to Earth's size.",
    "It orbits the Sun once every 225 Earth days.",
    'Venus has no moons.',
    "The clouds are made of sulfuric acid droplets.",
    "Venus is the brightest natural object in Earth's night sky after the Moon.",
  ],
  mars: [
    'Mars is the fourth planet from the Sun, known as the Red Planet.',
    'Its reddish color comes from iron oxide (rust) covering much of the surface.',
    "Mars has a radius of about 3,390 km, roughly half of Earth's.",
    'A day on Mars (a "sol") is about 24 hours 37 minutes, close to Earth\'s.',
    'A Martian year lasts about 687 Earth days.',
    'Mars has two small moons, Phobos and Deimos.',
    "Surface gravity is about 3.7 m/s², about 38% of Earth's.",
    'Mars is home to Olympus Mons, the tallest known volcano in the Solar System.',
    "The atmosphere is thin and mostly carbon dioxide.",
    'Average surface temperature is about -63°C.',
    'Mars has polar ice caps made of water ice and frozen carbon dioxide.',
  ],
};
